packageName=one.echobell.echobellandroid

monthlyProductId=echobell.subscription.monthly
monthlyBasePlanId=monthly
monthlyBillingPeriod=P1M

annualProductId=echobell.subscription.annual
annualBasePlanId=annual
annualBillingPeriod=P1Y
