packageName=one.echobell.echobellandroid

monthlyProductId=echobell.subscription.monthly
monthlyBasePlanId=monthly
monthlyBillingPeriod=P1M
monthlyTrialPeriod=P3D

annualProductId=echobell.subscription.annual
annualBasePlanId=annual
annualBillingPeriod=P1Y
annualTrialPeriod=P7D
